/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNI_Helper */

#ifndef _Included_JNI_Helper
#define _Included_JNI_Helper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JNI_Helper
 * Method:    displayMenuBeforeLogin
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JNI_Helper_displayMenuBeforeLogin
  (JNIEnv *, jobject);

/*
 * Class:     JNI_Helper
 * Method:    displayMenuAfterLogin
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JNI_Helper_displayMenuAfterLogin
  (JNIEnv *, jobject);

/*
 * Class:     JNI_Helper
 * Method:    displayStockOperationsMenu
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JNI_Helper_displayStockOperationsMenu
  (JNIEnv *, jobject);

/*
 * Class:     JNI_Helper
 * Method:    displayPortfolioMenu
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JNI_Helper_displayPortfolioMenu
  (JNIEnv *, jobject);

/*
 * Class:     JNI_Helper
 * Method:    getUserID
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_JNI_Helper_getUserID
  (JNIEnv *, jobject);

/*
 * Class:     JNI_Helper
 * Method:    getPassword
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_JNI_Helper_getPassword
  (JNIEnv *, jobject);

/*
 * Class:     JNI_Helper
 * Method:    registerUser
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_JNI_Helper_registerUser
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     JNI_Helper
 * Method:    login
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_JNI_Helper_login
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     JNI_Helper
 * Method:    logout
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JNI_Helper_logout
  (JNIEnv *, jobject);

/*
 * Class:     JNI_Helper
 * Method:    deleteAccount
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_JNI_Helper_deleteAccount
  (JNIEnv *, jobject);

/*
 * Class:     JNI_Helper
 * Method:    addMoneyToWallet
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_JNI_Helper_addMoneyToWallet
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     JNI_Helper
 * Method:    checkWalletBalance
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_JNI_Helper_checkWalletBalance
  (JNIEnv *, jobject);

/*
 * Class:     JNI_Helper
 * Method:    displayStockDetails
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JNI_Helper_displayStockDetails
  (JNIEnv *, jobject);

/*
 * Class:     JNI_Helper
 * Method:    buyStock
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_JNI_Helper_buyStock
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     JNI_Helper
 * Method:    sellStock
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_JNI_Helper_sellStock
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     JNI_Helper
 * Method:    displayPortfolio
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JNI_Helper_displayPortfolio
  (JNIEnv *, jobject);

/*
 * Class:     JNI_Helper
 * Method:    displayReturns
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JNI_Helper_displayReturns
  (JNIEnv *, jobject);

/*
 * Class:     JNI_Helper
 * Method:    showTransactionHistory
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JNI_Helper_showTransactionHistory
  (JNIEnv *, jobject);

/*
 * Class:     JNI_Helper
 * Method:    addToWatchlist
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_JNI_Helper_addToWatchlist
  (JNIEnv *, jobject, jstring);

/*
 * Class:     JNI_Helper
 * Method:    viewWatchlist
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JNI_Helper_viewWatchlist
  (JNIEnv *, jobject);

/*
 * Class:     JNI_Helper
 * Method:    handleStockChoice
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_JNI_Helper_handleStockChoice
  (JNIEnv *, jobject, jstring);

/*
 * Class:     JNI_Helper
 * Method:    sortPortfolio
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_JNI_Helper_sortPortfolio
  (JNIEnv *, jobject, jint);

/*
 * Class:     JNI_Helper
 * Method:    sortByProfit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JNI_Helper_sortByProfit
  (JNIEnv *, jobject);

/*
 * Class:     JNI_Helper
 * Method:    sortByLoss
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JNI_Helper_sortByLoss
  (JNIEnv *, jobject);

/*
 * Class:     JNI_Helper
 * Method:    sortByInvestment
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JNI_Helper_sortByInvestment
  (JNIEnv *, jobject);

/*
 * Class:     JNI_Helper
 * Method:    sortByReturns
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JNI_Helper_sortByReturns
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
